#cloud-config

users:
  - name: root
    passwd: $1$C3IPO/Q4$rh9psb.DS/2exW4mXaek50
    groups:
      - sudo
      - docker
      - wheel
      - systemd-journal
    ssh-authorized-keys:
      - <%= IO.read("/.ssh/id_rsa.pub") %>

coreos:
  update:
    reboot-strategy: off
  units:
# ExperimentalPlatform
    - name: test-timezone-protonet.service
      # command: start
      enable: true
      content: |
        [Unit]
        Description=Set the timezone

        [Service]
        RemainAfterExit=yes
        Type=oneshot
        ExecStart=/usr/bin/env timedatectl set-timezone Europe/Berlin
    - name: testing-config-skvs-protonet.service
      # command: start
      enable: true
      content: |
        [Unit]
        Description=Configure PTW
        After=skvs-protonet.service
        Requires=skvs-protonet.service

        [Service]
        ExecStart=/bin/bash -c "curl -X PUT -d value=protonet-test-integration.protonet.info http://$(docker inspect -f '{{ .NetworkSettings.IPAddress }}' skvs):80/ptw/nodename"
        KillMode=none
        Type=oneshot
        RemainAfterExit=yes

        [Install]
        WantedBy=multi-user.target
    - name: testing-all-clear-signal-protonet.service
      # command: start
      enable: true
      content: |
        [Unit]
        Description=Send an all clear signal
        After=testing-config-skvs-protonet.service dokku-protonet.service
        Requires=testing-config-skvs-protonet.service dokku-protonet.service

        [Service]
        Type=idle
        TimeoutStartSec=10
        ExecStartPre=/bin/bash -c 'docker ps | grep dokku'
        ExecStart='/usr/bin/ncat -c "echo OKAY" -l -k  42423'
        Restart=always
        RestartSec=30s

        [Install]
        WantedBy=multi-user.target



