#cloud-config

users:
  - name: root
    passwd: $6$0f1Xl822UWa2sxRC$08OPTYpq5.8Cfc1Xm3LwcfraZrsDaUP.V5285VmhPdwSsfSw4VRBSY27qoofXLFMl4Uc0GvDJjlvH8IDYPeca0
    groups:
      - sudo
      - docker
      - wheel
      - systemd-journal
    ssh-authorized-keys:
      - <%= IO.read("/.ssh/id_rsa.pub") %>

coreos:
  update:
    reboot-strategy: off
  units:
# ExperimentalPlatform
    - name: testing-config-skvs-protonet.service
      # command: start
      enable: true
      content: |
        [Unit]
        Description=Configure PTW
        After=skvs-protonet.service
        Requires=skvs-protonet.service

        [Service]
        ExecStart=/bin/bash -c "curl -X PUT -d value=protonet-test-integration.protonet.info http://$(docker inspect -f '{{ .NetworkSettings.IPAddress }}' skvs):80/ptw/nodename"
        KillMode=none
        Type=oneshot
        RemainAfterExit=yes

        [Install]
        WantedBy=multi-user.target
